name: setup
description: setup mise and pnpm

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

    - id: pnpm-cache
      run: |
        echo "store-path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v5
      with:
        path: ${{ steps.pnpm-cache.outputs.store-path }}
        key: pnpm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-${{ runner.arch }}-

    - run: pnpm install --frozen-lockfile
      shell: bash
