name: setup
description: setup mise and pnpm

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

    - id: pnpm-cache
      run: |
        echo "store-path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v5
      with:
        path: ${{ steps.pnpm-cache.outputs.store-path }}
        key: pnpm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-${{ runner.arch }}-

    - run: pnpm install --frozen-lockfile
      shell: bash
