name: setup
description: setup mise and pnpm

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

    - id: pnpm-cache
      run: |
        echo "store-path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ steps.pnpm-cache.outputs.store-path }}
        key: pnpm-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-${{ runner.arch }}-

    - run: pnpm install --frozen-lockfile
      shell: bash
