name: docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yaml
      - docs/**
  workflow_dispatch:

jobs:
  build-pages:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
      - uses: actions/upload-pages-artifact@v4

  deploy-pages:
    needs: build-pages
    runs-on: ubuntu-slim
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
