name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
      - run: pnpm test
      - uses: h3y6e/action-slack@v4
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,job,took,ref,workflowRun,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
